#!/usr/bin/python
import sys,re,os,string
import commands
import os

## This program implements the following aliases
#alias kjoball "qstat | grep zyang03 | gawk '{print $1}' | xargs qdel"
prefix = None
user = os.environ['USER']
if len(sys.argv) >= 2:
  prefix = sys.argv[1]
if prefix is None:
  cmd1 = "qstat | grep %s | gawk \'{print $1}\' | xargs qdel" % (user)
  print cmd1
else:
  cmd1 = "qstat -a | grep %s | grep %s | gawk \'{print $1}\' " % (prefix, user)
  stat1,out1=commands.getstatusoutput(cmd1)
  # extract the list of outputs
  jobns = []
  for line in out1.split('\n'):
    jobns.append(line.split('.')[0])
  cmd2 = "qdel %s" % " ".join(jobns)
  print cmd2
  os.system(cmd2)
#os.system(cmd1)

